### ISSUE TITLE
System.OverflowException: Value was either too large or too small for a UInt64

### ISSUE THREAD

**Issue by Shrulik** [mono/Embeddinator-4000#15]
I have tried to convert the Azure IoT Hub C# SDK to run natively on iOS. 
https://www.nuget.org/packages/Microsoft.Azure.Devices.Client.PCL/

When I tried to compile(?) it , I got the following error. Am I doing something wrong ? 

````
PS C:\Users\YuriK\Documents\Visual Studio 2015\Projects\XamarinSource\XamarinSource\bin\Debug> C:\Users\YuriK\dev\work\Embeddinator-4000\build\lib\Debug\MonoEmbeddinator4000.exe --gen=obj-c
 -p=ios -o =C:\Users\YuriK\dev\work\conv2 -d --shared --vs=2015 -v .\Microsoft.Azure.Devices.Client.PCL.dll
Parsing assemblies...
    Parsed 'Microsoft.Azure.Devices.Client.PCL.dll'
Processing assemblies...

Unhandled Exception: System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Convert.ToUInt64(Int32 value)
   at System.Int32.System.IConvertible.ToUInt64(IFormatProvider provider)
   at System.Convert.ToUInt64(Object value)
   at MonoEmbeddinator4000.Generators.ASTGenerator.VisitEnum(TypeInfo type) in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Generators\AstGenerator.cs:line 144
   at MonoEmbeddinator4000.Generators.ASTGenerator.Visit(TypeInfo typeInfo) in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Generators\AstGenerator.cs:line 91
   at MonoEmbeddinator4000.Generators.ASTGenerator.Visit(Assembly assembly) in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Generators\AstGenerator.cs:line 56
   at MonoEmbeddinator4000.Driver.Process() in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Driver.cs:line 76
   at MonoEmbeddinator4000.Driver.Run() in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Driver.cs:line 231
   at MonoEmbeddinator4000.CLI.Main(String[] args) in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\CLI.cs:line 182
````

**Comment by tritao** [comment]
Seems like just a bug... Let me try to reproduce it.

**Comment by tritao** [comment]
This is an implementation issue with handling signed / negative values enum item types.

I pushed a work-in-progress fix... but it needs further testing which I can't do right now.

I've pushed it to unblock you, will be giving it a little more testing and fix any issues later in the day.

**Comment by Shrulik** [comment]
Thanks for the help. After pulling the changes, I got the same error as in #6 "Basic.Managed.h". Earlier I had some problems in my VS 2015 install so I'm going to clean things a bit and see if it still happens.

**Comment by Shrulik** [comment]
I still get 'Basic.Manged.h'. I have tried running the code again after the fix, and I get a different error, even on my 'HelloWorld' library with one method in it. This is the error:

````
C:\Users\YuriK\dev\work\Embeddinator-4000\build\lib\Debug\MonoEmbeddinator4000.exe --gen=obj-c -p=ios -d -o=atmpt1/ --share
d --vs=2015 -v C:\Users\YuriK\dev\work\ClassLibrary1\ClassLibrary1\bin\Debug\ClassLibrary1.dll
Parsing assemblies...
    Parsed 'ClassLibrary1.dll'
Processing assemblies...
    Pass 'MonoEmbeddinator4000.CheckReservedKeywords'
    Pass 'MonoEmbeddinator4000.Passes.FixMethodParametersPass'
    Pass 'MonoEmbeddinator4000.Passes.GenerateObjectTypesPass'
    Pass 'MonoEmbeddinator4000.Passes.GenerateArrayTypes'
    Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Pass 'MonoEmbeddinator4000.Passes.RenameEnumItemsPass'
    Pass 'MonoEmbeddinator4000.Passes.RenameDuplicatedDeclsPass'
    Pass 'CppSharp.Passes.CheckDuplicatedNamesPass'
Generating binding code...

Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at MonoEmbeddinator4000.Generators.CGenerator.TypePrinterDelegate(Type type) in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Generators\C\CGenerator.cs:line 69
   at System.Func`2.Invoke(T arg)
   at CppSharp.AST.Type.ToString() in C:\Users\YuriK\dev\work\Embeddinator-4000\external\CppSharp\src\AST\Type.cs:line 37
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1, Object arg2)
   at MonoEmbeddinator4000.Generators.ObjCExtensions.GenerateObjCField(CCodeGenerator gen, Field field) in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Generators\ObjC\ObjCGenerator.cs:line 58
   at MonoEmbeddinator4000.Generators.ObjCHeaders.VisitFieldDecl(Field field) in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Generators\ObjC\ObjCHeaders.cs:line 61
   at CppSharp.AST.Field.Visit[T](IDeclVisitor`1 visitor) in C:\Users\YuriK\dev\work\Embeddinator-4000\external\CppSharp\src\AST\Field.cs:line 38
   at MonoEmbeddinator4000.Generators.ObjCHeaders.VisitClassDecl(Class class) in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Generators\ObjC\ObjCHeaders.cs:line 44
   at CppSharp.AST.Class.Visit[T](IDeclVisitor`1 visitor) in C:\Users\YuriK\dev\work\Embeddinator-4000\external\CppSharp\src\AST\Class.cs:line 293
   at CppSharp.Generators.CodeGenerator.VisitDeclContext(DeclarationContext context) in C:\Users\YuriK\dev\work\Embeddinator-4000\external\CppSharp\src\Generator\Generators\CodeGenerator.cs:line 253
   at CppSharp.Generators.CodeGenerator.VisitNamespace(Namespace namespace) in C:\Users\YuriK\dev\work\Embeddinator-4000\external\CppSharp\src\Generator\Generators\CodeGenerator.cs:line 315
   at CppSharp.AST.Namespace.Visit[T](IDeclVisitor`1 visitor) in C:\Users\YuriK\dev\work\Embeddinator-4000\external\CppSharp\src\AST\Namespace.cs:line 460
   at CppSharp.Generators.CodeGenerator.VisitDeclContext(DeclarationContext context) in C:\Users\YuriK\dev\work\Embeddinator-4000\external\CppSharp\src\Generator\Generators\CodeGenerator.cs:line 253
   at MonoEmbeddinator4000.Generators.CHeaders.Process() in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Generators\C\CHeaders.cs:line 46
   at MonoEmbeddinator4000.Generators.ObjCHeaders.Process() in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Generators\ObjC\ObjCHeaders.cs:line 16
   at MonoEmbeddinator4000.Driver.Generate() in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Driver.cs:line 162
   at MonoEmbeddinator4000.Driver.Run() in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\Driver.cs:line 236
   at MonoEmbeddinator4000.CLI.Main(String[] args) in C:\Users\YuriK\dev\work\Embeddinator-4000\binder\CLI.cs:line 182
````

**Comment by tritao** [comment]
Looking into it.

**Comment by tritao** [comment]
@Shrulik That issue should be fixed.

**Comment by tritao** [comment]
About the `Basic.Managed.h` build failure, you can ignore it for now. It's some problem with the Windows build, will fix it once I have access to a Windows box.
