### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by MihaMarkic** [mono/Embeddinator-4000#6]
Freshly git cloned project wont build because:
a) CppSharp.Generator is missing Mono.Cecil assembly
b) catch.hpp file is missing by Basic.Tests.

The workaround to a) is to install Mono.Cecil from NuGet (should I create a pull request?) as for the second I don't know (tests can be omitted for the moment I guess).

**Comment by tritao** [comment]
As you found you need to initialize the Git submodules.

Fixed by https://github.com/mono/Embeddinator-4000/pull/7.

**Comment by MihaMarkic** [comment]
@tritao But that doesn't help in this case. Mono.Cecil is still missing, instead of catch.hpp now it complains about Basic.Managed.h. That's why I didn't close this issue.

**Comment by tritao** [comment]
Sorry, thought it was fixed.

We do not really depend on Cecil directly, did some digging and it was added as an indirect dependency for CppSharp. I'll see about getting this fixed.

About `Basic.Managed.h`, can you tell me where the error message comes from? Is it at build time?

**Comment by MihaMarkic** [comment]
Yes, build time on Basic.Tests.cpp.

> MYPATH\embeddinator-4000\tests\basic\basic.tests.cpp(4): fatal error C1083: Cannot open include file: 'Basic.Managed.h': No such file or directory

**Comment by MihaMarkic** [comment]
(and indeed such file is nowhere on my computer)

**Comment by tritao** [comment]
I've been able to reproduce that issue, something on the build files got regressed, I will take a look.

**Comment by tritao** [comment]
This one should be fixed now
